<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var giiant\sakila\models\DeptManager $model
*/

$this->title = 'Dept Manager ' . $model->dept_no;
$this->params['breadcrumbs'][] = ['label' => 'Dept Managers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->dept_no, 'url' => ['view', 'dept_no' => $model->dept_no, 'emp_no' => $model->emp_no]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="dept-manager-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List'), ['index'], ['class'=>'btn btn-default']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'dept_no' => $model->dept_no, 'emp_no' => $model->emp_no],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
                        <?= $model->dept_no ?>        </div>

        <div class="panel-body">



    <?php $this->beginBlock('giiant\sakila\models\DeptManager'); ?>

    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'dept_no',
    'value' => ($model->getDeptNo()->one() ? Html::a($model->getDeptNo()->one()->dept_no, ['departments/view', 'dept_no' => $model->getDeptNo()->one()->dept_no,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'emp_no',
    'value' => ($model->getEmpNo()->one() ? Html::a($model->getEmpNo()->one()->emp_no, ['employees/view', 'emp_no' => $model->getEmpNo()->one()->emp_no,]) : '<span class="label label-warning">?</span>'),
],
			'from_date',
			'to_date',
    ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'dept_no' => $model->dept_no, 'emp_no' => $model->emp_no],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<span class="glyphicon glyphicon-asterisk"></span> DeptManager',
    'content' => $this->blocks['giiant\sakila\models\DeptManager'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
