<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var giiant\sakila\models\Rental $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="panel panel-default">
    <div class="panel-heading">
                <?= $model->rental_id ?>    </div>

    <div class="panel-body">

        <div class="rental-form">

            <?php $form = ActiveForm::begin([
            'id' => 'Rental',
            'layout' => 'horizontal',
            'enableClientValidation' => false,
            ]
            );
            ?>

            <div class="">
                <?php echo $form->errorSummary($model); ?>
                <?php $this->beginBlock('main'); ?>

                <p>
                    
			<?= $form->field($model, 'rental_date')->textInput() ?>
			<?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'inventory_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(giiant\sakila\models\Inventory::find()->all(),'inventory_id','inventory_id'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'customer_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(giiant\sakila\models\Customer::find()->all(),'customer_id','customer_id'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'staff_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(giiant\sakila\models\Staff::find()->all(),'staff_id','staff_id'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
			<?= $form->field($model, 'return_date')->textInput() ?>
			<?= $form->field($model, 'last_update')->textInput() ?>
                </p>
                <?php $this->endBlock(); ?>
                
                <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Rental',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
                <hr/>

                <?= Html::submitButton(
                '<span class="glyphicon glyphicon-check"></span> ' . ($model->isNewRecord
                ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
                [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
                ]
                );
                ?>

                <?php ActiveForm::end(); ?>

            </div>

        </div>

    </div>

</div>
