<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var giiant\sakila\models\Payment $model
*/

$this->title = 'Payment ' . $model->payment_id;
$this->params['breadcrumbs'][] = ['label' => 'Payments', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->payment_id, 'url' => ['view', 'payment_id' => $model->payment_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="payment-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List'), ['index'], ['class'=>'btn btn-default']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'payment_id' => $model->payment_id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
                        <?= $model->payment_id ?>        </div>

        <div class="panel-body">



    <?php $this->beginBlock('giiant\sakila\models\Payment'); ?>

    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    			'payment_id',
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'customer_id',
    'value' => ($model->getCustomer()->one() ? Html::a($model->getCustomer()->one()->customer_id, ['customer/view', 'customer_id' => $model->getCustomer()->one()->customer_id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'staff_id',
    'value' => ($model->getStaff()->one() ? Html::a($model->getStaff()->one()->staff_id, ['staff/view', 'staff_id' => $model->getStaff()->one()->staff_id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'rental_id',
    'value' => ($model->getRental()->one() ? Html::a($model->getRental()->one()->rental_id, ['rental/view', 'rental_id' => $model->getRental()->one()->rental_id,]) : '<span class="label label-warning">?</span>'),
],
			'amount',
			'payment_date',
			'last_update',
    ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'payment_id' => $model->payment_id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<span class="glyphicon glyphicon-asterisk"></span> Payment',
    'content' => $this->blocks['giiant\sakila\models\Payment'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
